### PR TITLE
Fixed Issue.

### PR DESCRIPTION
**Pull request by VANITAX**
They was not working. So I fixed some Issue. See commit

### CODE REVIEW

**Comment by JefferyHus** [comment]
what OS you are working on?

**Comment by VANITAX** [comment]
Hi @JefferyHus  "express": "^4.15.2" with node:8.9.2

**Comment by JefferyHus** [comment]
OS is operating System: Linux, Windows or MacOS?

**Comment by VANITAX** [comment]
Sorry I misunderstood. it working on macOS 10.13.4

but my environment is running in docker container `node:8.9.2 - alpine `

**Comment by JefferyHus** [comment]
because the changes you did will break it for Windows users (i'm one), cross-env makes it so you can have a single command without worrying about setting or using the environment variable properly for the platform. Just set it like you would if it's running on a POSIX system, and cross-env will take care of setting it properly.  (from https://www.npmjs.com/package/cross-env)
Also in `.gitignore` you added `.yarn-cache/` while I have used `npm`, but this is not a problem as it helps people whom wants to contribute and use yarn instead, so thanks for that.
Would you like to explain why you have changed the constructor?

**Comment by VANITAX** [comment]
- `cross-env` 
Sorry about platform's issue. I ignored

- `Would you like to explain why you have changed the constructor?` 
Because `request` this parameter is included  `headers`, `userAgent`.  So I don't understand. Why want to split `request` ? If follow the example. I will get error.

**Comment by JefferyHus** [comment]
can you share your code with me please so we can find a good solution for everyone 👍

**Pull request closed without merging**
