### PR TITLE
[feat] add index.d.ts

### PR DESCRIPTION
**Pull request by ardok**
* Add index.d.ts for better types in typescript projects.
* Unsure whether this will compile fine though....

### CODE REVIEW

**Comment by ardok** [comment]
@JefferyHus do double-check. I'm not sure whether it will compile fine, I guess. And I'm not sure about the types either. You probably know more.

**Comment by JefferyHus** [comment]
thank you so much for the contribution, I am reviewing and testing...

**Comment by ardok** [comment]
If it's faster, feel free to create your own PR if you find something that needs to be changed from my PR. Just copy paste and change what I have done here.

**Comment by JefferyHus** [comment]
@ardok checkout [this PR](https://github.com/JefferyHus/es6-crawler-detect/pull/60) it does migrate the whole project to typescript.

**Pull request closed without merging**
